name: Build And Deploy Dist

on:
  push:
    branches:
      - main 
    schedule:
      - cron: '50 */2 * * *'
jobs:
  copy_repo:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: 'true'

    - name: Copy
      run: |
        shopt -u dotglob
        cp -r ./repo/* ./dist/
        echo "Size: $(du -sh ./dist)"
        echo "Amount: $(tree ./dist |wc -l)"
        

