name: Update And Deploy Dist

on:
  push:
  schedule:
    - cron: '50 */2 * * *'

jobs:
  update:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: recursive
        fetch-depth: 1
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Copy
      run: bash build.sh
        
    - name: Deploy
      run: |
        pip install https://github.com/tencentyun/coscmd/archive/refs/heads/master.zip
        echo "[common]" > ~/.cos.conf
        echo "secret_id = ${{ secrets.SECRET_ID }}" >> ~/.cos.conf
        echo "secret_key = ${{ secrets.SECRET_KEY }}" >> ~/.cos.conf
        echo "bucket = ${{ secrets.COS_BUCKET }}" >> ~/.cos.conf
        echo "region = ${{ secrets.COS_REGION }}" >> ~/.cos.conf
        echo "max_thread = 5" >> ~/.cos.conf
        echo "part_size = 1" >> ~/.cos.conf
        echo "retry = 5" >> ~/.cos.conf
        echo "timeout = 60" >> ~/.cos.conf
        echo "schema = https" >> ~/.cos.conf
        echo "verify = md5" >> ~/.cos.conf
        echo "anonymous = False" >> ~/.cos.conf
        coscmd -b ${{ secrets.COS_BUCKET }} -r ${{ secrets.COS_REGION }} upload -rs ./dist/ /

    - name: Record
      run: |
        echo "$(date -u +'%Y-%m-%d %H:%M:%S UTC')" > last_update
        git config --global user.name "GitHub Action"
        git config --global user.email "action@github.com"
        git add last_update
        git commit -m "update" || echo "No changes to commit"
        git push
